dataset_name: cifar10
model_name: GatedGCN
net_params:
  L: 4
  batch_norm: true
  device: &id001 !!python/object/apply:torch.device
  - cuda
  - 0
  dropout: 0.0
  edge_feat: false
  gated: false
  hidden_dim: 70
  in_dim: 5
  in_dim_edge: 1
  in_feat_dropout: 0.0
  layer_norm: true
  n_classes: 10
  n_heads: -1
  out_dim: 70
  readout: mean
  residual: true
  self_loop: false
  total_param: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    pZcBAAAAAAA=
params:
  batch_size: 5
  device: *id001
  epochs: 1000
  init_lr: 5.0e-05
  lr_reduce_factor: 0.5
  lr_schedule_patience: 25
  max_time: 12
  min_lr: 1.0e-06
  n_sp_test: null
  out: ./out
  print_epoch_interval: 5
  rotated_angle: 0
  seed: 41
  snr: null
  weight_decay: 0
